name: Lint Code Base

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/Dockerfile'
      - 'scripts/**'
      - 'etc/litestream.yml'
      - .github/workflows/ci-lint-codebase.yml

permissions: read-all

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job not required"
